<?php

namespace ProcessWire;

class WesanoxBasicBlog extends WireData implements Module, ConfigurableModule
{
    public static function getModuleInfo()
    {
        return array(
            'title' => 'wesanox Blog Tool',
            'summary' => 'A little News Tool for Processwire made by wesanox.',
            'version' => '0.1.1',
            'author' => 'Frittenfritze',
            'icon' => 'newspaper-o',
            'autoload' => true,
            'installs' => ['ProcessWesanoxBasicBlog', 'FieldtypeDynamicOptions','WesanoxMatrixContent'],
            'requires' => array(
                'ProcessWire>=3.0.210',
                'PHP>=8.0.0',
                'WesanoxMatrixContent>=0.0.1'
            ),
        );
    }

    protected array $internal_modules = [
        'FieldtypeDynamicOptions',
    ];

    protected array $external_modules = [
        'WesanoxMatrixContent' => 'https://github.com/wesanox/WesanoxMatrixContent/archive/refs/heads/main.zip',
    ];

    protected array $content_fields = [
        'repeater_categories_news',
        'checkbox_subcategory',
        'tab_news',
        'tab_news_END',
        'dynamic_categories_news',
        'dynamic_subcategories_news',
        'date_news',
        'text',
        'image',
    ];

    public function __construct()
    {
        /**
         * set the Template Names
         */
        $this->template_news = 'template_news';
        $this->template_options  = 'options_generals';
        $this->template_options_news  = 'options_news';
    }

    /**
     * install function for the module
     *
     * @return void
     * @throws WirePermissionException
     */
    public function ___install()
    {
        foreach ($this->internal_modules as $moduleName) {
            if (!$this->modules->isInstalled($moduleName)) {
                $this->modules->get($moduleName);
            }
        }

        /**
         * create / copy the template_news.php in the templates folder
         */
        $tplFile = $this->config->paths->WesanoxBasicBlog . 'src/templates/' .  $this->template_news . '.php';
        $targetFile = $this->config->paths->templates . $this->template_news . '.php';

        if (!file_exists($targetFile)) {
            copy($tplFile, $targetFile);
        }

        /**
         * create the fields for the custom menu
         */
        $this->createFields($this->fields);

        /**
         * if not exists, create content only Page
         */
        if ( !$this->templates->get($this->template_news) ) {
            $fg = new Fieldgroup();
            $fg->name = $this->template_news;
            $fg->add('title');
            $fg->add('dynamic_categories_news');
            $fg->add('dynamic_subcategories_news');
            $fg->add('date_news');

            $fg->add('image');
//            $fg->get('image')->set('columnWidth', 50);
//            $fg->get('image')->save();

            $fg->add('text');
//            $fg->get('text')->set('columnWidth', 50);
//            $fg->get('text')->set('label', 'Kurzbeschreibung');
//            $fg->get('text')->save();

            $fg->add('matrix_content');
            $fg->save();

            $tn = new Template();
            $tn->name = $this->template_news;
            $tn->label = 'News';
            $tn->fieldgroup = $fg;
            $tn->icon = 'Newspaper-o';
            $tn->tags = 'Templates';
            $tn->save();
        } else {
            $tn = $this->fieldgroups->get($this->template_news);
            $tn->add('dynamic_categories_news');
            $tn->add('dynamic_subcategories_news');
            $tn->add('date_news');

            $tn->add('image');
//            $tn->get('image')->set('columnWidth', 50);
//            $tn->get('image')->save();

            $tn->add('text');
//            $tn->get('text')->set('columnWidth', 50);
//            $tn->get('text')->set('label', 'Kurzbeschreibung');
//            $tn->get('text')->save();

            $tn->add('matrix_content');
            $tn->save();
        }

        /**
         * if not exists, create settings Page
         */
        if ( !$this->templates->get($this->template_options) ) {
            $op = new Template();
            $op->name = $this->template_options;
            $op->label = 'Einstellungen';
            $op->fieldgroup = $fg;
            $op->icon = 'cogs';
            $op->tags = 'Options';
            $op->noParents = -1;
            $op->save();
        }

        /**
         * if not exists, create settings news Page or add new Fields
         * to the settingsnewspage
         */
        if ( !$this->templates->get($this->template_options_news) ) {
            $fg = new Fieldgroup();
            $fg->name = $this->template_options_news;
            $fg->add('title');
            $fg->add('matrix_basic');
            $fg->add('tab_news');
            $fg->add('repeater_categories_news');
            $fg->add('tab_news_END');
            $fg->save();

            $op = new Template();
            $op->name = $this->template_options_news;
            $op->label = 'News Einstellungen';
            $op->fieldgroup = $fg;
            $op->icon = 'cogs';
            $op->tags = 'Options';
            $op->noParents = -1;
            $op->save();
        } else {
            $op = $this->fieldgroups->get($this->template_options_news);
            $op->add('matrix_basic');
            $op->add('tab_news');
            $op->add('repeater_categories_news');
            $op->add('tab_news_END');
            $op->save();
        }

        $np = new Page();
        $np->template = $this->template_options_news;
        $np->parent = $this->pages->get('template=options_generals');
        $np->title = 'News Einstellungen';
        $np->name = 'options-news';
        $np->save();
    }

    /**
     * uninstall function for the modul
     *
     * @return void
     * @throws WireException
     */
    public function ___uninstall()
    {
        /**
         * remove the settings page
         */
        if($this->pages->get('name=options-news')) {
            $this->pages->get('name=options-news')->delete();
        }

        /**
         * remove fields from news page
         */
        if($this->templates->get($this->template_news)) {
            $op = $this->fieldgroups->get($this->template_news);
            $op->remove('matrix_content');
            $op->save();
        }

        /**
         * remove fields from option page
         */
        if($this->templates->get($this->template_options_news)) {
            $op = $this->fieldgroups->get($this->template_options_news);
            $op->remove('matrix_basic');
            $op->remove('tab_news');
            $op->remove('repeater_categories_news');
            $op->remove('tab_news_END');
            $op->save();
        }

        /**
         * remove template_news.php from templates folder
         */
        $file = $this->config->paths->templates . "$this->template_news.php";

        if (is_file($file)) {
            unlink($file);
        }

        if ($this->templates->get($this->template_news)->id && !$this->pages->count("template=$this->template_news")) {
            $this->templates->delete($this->templates->get($this->template_news));
        }

        /**
         * delete fields
         */
        foreach ($this->content_fields as $field_name) {
            $field = $this->fields->get($field_name);

            if ($field && $field->getFieldgroups()->count == 0) {
                $this->fields->delete($field);
            }
        }

        if($this->templates->get($this->template_options_news)->id && !$this->pages->count("template=$this->template_options_news")) {
            $this->templates->delete($this->templates->get($this->template_options_news));
        }
    }

    /**
     * Modul-Konfiguration
     */
    public static function getModuleConfigInputfields(array $data) : InputfieldWrapper
    {
        $inputfields = new InputfieldWrapper();

        /**
         * Represents a variable named $f.
         *
         * The purpose and type of this variable should be defined
         * based on its usage in the application. Ensure that
         * adequate context is provided where this variable is utilized.
         */
//        $f = wire('modules')->get('InputfieldCheckbox');
//        $f->name = 'remove_language_modules';
//        $f->label = __('Sprachmodule beim Deinstallieren automatisch entfernen');
//        $f->description = __('Achtung: Diese Option entfernt Sprachunterstützung dauerhaft.');
//        $f->value = 1;
//        $f->columnWidth = 50;
//        $f->checked = !empty($data['remove_language_modules']);
//        $inputfields->add($f);
//
//        $f = wire('modules')->get('InputfieldCheckbox');
//        $f->name = 'easy_language';
//        $f->label = __('Sprache "Einfache Sprache" hinzufügen');
//        $f->description = __('Fügt eine neue Sprache mit dem Namen "einfache-sprache" hinzu.');
//        $f->value = 1;
//        $f->columnWidth = 50;
//        $f->checked = !empty($data['easy_language']);
//        $inputfields->add($f);

        return $inputfields;
    }

    /**
     * @return void
     */
    public function ready() : void
    {
        $this->addHookAfter('FieldtypeDynamicOptions::getSelectableOptions', $this, 'provideDynamicCategoriesNews');
        $this->addHookAfter('FieldtypeDynamicOptions::getSelectableOptions', $this, 'provideDynamicSubcategoriesNews');
    }

    /**
     * @param HookEvent $event
     * @return void
     */
    public function provideDynamicCategoriesNews(HookEvent $event) : void
    {
        $field = $event->arguments(1);

        if ($field->name === 'dynamic_categories_news') {
            $settingsPage = $this->pages->get('template='.$this->template_options_news);
            $options = [];

            foreach ($settingsPage->repeater_categories_news as $cat) {
                if (!$cat->checkbox_subcategory) {
                    $options[$cat->id] = $cat->headline;
                }
            }

            $event->return = $options;
        }
    }

    /**
     * @param HookEvent $event
     * @return void
     */
    public function provideDynamicSubcategoriesNews(HookEvent $event) : void
    {
        $field = $event->arguments(1);

        if ($field->name === 'dynamic_subcategories_news') {
            $settingsPage = $this->pages->get('template='.$this->template_options_news);
            $options = [];

            foreach ($settingsPage->repeater_categories_news as $cat) {
                if ($cat->checkbox_subcategory) {
                    $options[$cat->id] = $cat->headline;
                }
            }

            $event->return = $options;
        }
    }

    private function createFields($fields) : void
    {
        /**
         * headline
         */
        if(!$fields->get('headline')) {
            $f = new Field;
            $f->type = $this->modules->get('FieldtypeText');
            $f->name = "headline";
            $f->label = $this->_('Überschrift');
            $f->tags = 'headlines';
            $f->icon = 'Header';
            $f->textformatters = [0 => 'TextformatterEntities'];
            $f->columnWidth = 25;
            $f->save();
        }

        if(!$fields->get('checkbox_subcategory')) {
            $f = new Field;
            $f->type = $this->modules->get('FieldtypeCheckbox');
            $f->name = "checkbox_subcategory";
            $f->label = $this->_('Subcategory?');
            $f->description = $this->_('Is this a subcategory?');
            $f->tags = 'settings';
            $f->icon = 'Check';
            $f->columnWidth = 50;
            $f->save();
        }

        /**
         * tabs for the menu in the settings page
         */
        if(!$fields->get('tab_news')) {
            $f = new Field;
            $f->type = $this->modules->get('FieldtypeFieldsetTabOpen');
            $f->name = "tab_news";
            $f->label = $this->_('News Kategorien');
            $f->tags = 'tabs';
            $f->icon = 'Tag';
            $f->save();
        }

        if(!$fields->get('tab_news_END')) {
            $f = new Field;
            $f->type = $this->modules->get('FieldtypeFieldsetClose');
            $f->name = "tab_news_END";
            $f->label = $this->_('Close an open fieldset');
            $f->tags = 'tabs';
            $f->icon = 'Tag';
            $f->save();
        }

        /**
         * dynamic categories / subcategories news
         */
        if(!$fields->get('dynamic_categories_news')) {
            $f = new Field;
            $f->type = $this->modules->get('FieldtypeDynamicOptions');
            $f->name = "dynamic_categories_news";
            $f->label = $this->_('News Kategorien');
            $f->tags = 'dynamic';
            $f->icon = 'Magic';
            $f->max_items = 1;
            $f->columnWidth = 40;
            $f->inputfield_class = 'InputfieldCheckboxes';
            $f->save();
        }

        if(!$fields->get('dynamic_subcategories_news')) {
            $f = new Field;
            $f->type = $this->modules->get('FieldtypeDynamicOptions');
            $f->name = "dynamic_subcategories_news";
            $f->label = $this->_('News Subkategorien');
            $f->tags = 'dynamic';
            $f->icon = 'Magic';
            $f->columnWidth = 40;
            $f->inputfield_class = 'InputfieldCheckboxes';
            $f->save();
        }

        /**
         * date news
         */
        if(!$fields->get('date_news')) {
            $f = new Field;
            $f->type = $this->modules->get('FieldtypeDatetime');
            $f->name = "date_news";
            $f->label = $this->_('Veröffentlichungsdatum');
            $f->tags = 'date';
            $f->icon = 'Calendar';
            $f->dateOutputFormat = 'd.m.Y';
            $f->dateInputFormat = 'Y-m-d';
            $f->defaultToday = 1;
            $f->columnWidth = 20;
            $f->save();
        }

        /**
         * image
         */
        if(!$fields->get('image')) {
            $crop_image =
                <<<EOT
                desktop,1920,1080
                tablet,1024,600
                mobile,600,600
                quadratisch,750,750
                EOT;

            $f = new Field;
            $f->type = $this->modules->get('FieldtypeCroppableImage3');
            $f->name = "image";
            $f->label = $this->_('Bild');
            $f->tags = 'images';
            $f->icon = 'File image o';
            $f->columnWidth = 25;
            $f->maxFiles = 1;
            $f->defaultValuePage = 0;
            $f->gridMode = 'list';
            $f->clientQuality = 90;
            $f->extensions = 'gif jpg jpeg png';
            $f->cropSetting = $crop_image;
            $f->inputfieldClass = 'InputfieldCroppableImage3';
            $f->save();

            $f = $fields->get('image');
            $f->save();
        }

        /**
         * text
         */
        if(!$fields->get('text')) {
            $f = new Field;
            $f->type = $this->modules->get('FieldtypeTextarea');
            $f->name = "text";
            $f->label = $this->_('Text');
            $f->tags = 'text';
            $f->icon = 'File text o';
            $f->inputfieldClass = 'InputfieldCKEditor';
            $f->columnWidth = 100;
            $f->save();
        }

        /**
         * repeater for the news categories / subcategories
         */
        if(!$fields->get('repeater_categories_news')) {
            $id_headline = $fields->get('headline')->id;
            $id_checkbox_subcategory = $fields->get('checkbox_subcategory')->id;

            $f = new Field();
            $f->type = $this->modules->get("FieldtypeRepeater");
            $f->name = 'repeater_categories_news';
            $f->label = $this->_('Repeater (News Kategorien)');
            $f->tags = 'repeater';
            $f->icon = 'Repeat';
            $f->addType = 1;

            $f->repeaterFields = array(
                0 => $id_headline,
                1 => $id_checkbox_subcategory
            );

            $f->save();

            $repeater = $fields->get('repeater_categories_news');

            $repeater_template = $repeater->type->getRepeaterTemplate($repeater);

            $repeater_template->fieldgroup->add('headline');
            $repeater_template->fieldgroup->add('checkbox_subcategory');

            $repeater_template->fieldgroup->save();

            $repeater->save();
        }
    }
}